title: Kanbu
description: Project Management System
theme: jekyll-theme-primer
markdown: kramdown

# Plugins
plugins:
  - jekyll-seo-tag
    - jekyll-github-metadata

    # Repository
    repository: hydro13/kanbu

    # Exclude files from Jekyll processing
    exclude:
      - node_modules
        - .git
          - "*.json"
            - "*.js"
              - "*.yml"
                - docker-compose.yml
                  - Dockerfile
                    - apps
                      - packages
                        - scripts
                          - docs
